version: "3"

services:
  #  mysql:
  #    restart: always
  #    image: mysql:latest
  #    container_name: mysql
  #    volumes:
  #      - ./mydir:/mydir
  #      - ./datadir:/var/lib/mysql
  #      - ./conf/my.cnf:/etc/my.cnf
  #      数据库还原目录 可将需要还原的sql文件放在这里
  #      - /docker/mysql/source:/docker-entrypoint-initdb.d
  #    environment:
  #      - "MYSQL_ROOT_PASSWORD=root"
  #      - "MYSQL_DATABASE=keycloak-db"
  #      - "TZ=Asia/Shanghai"
  #    ports:
  #      - 3306:3306
  mariadb:
    image: mariadb:10.5.5
    container_name: "mariadb"
    #    restart: always
    environment:
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "root"
      MYSQL_ROOT_PASSWORD: "root"
      TZ: "Asia/Shanghai"
      MYSQL_DATABASE: "keycloak_db"
    ports:
      - "3306:3306"


  keycloak:
    image: quay.io/keycloak/keycloak:latest
    #    restart: always
    container_name: "keycloak"
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: "mariadb"
      KC_DB_URL: "jdbc:mariadb://mariadb:3306/keycloak_db?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&allowPublicKeyRetrieval=true"
      KC_DB_USERNAME: root
      KC_DB_PASSWORD: root
    depends_on:
      - mariadb
    command: 'start-dev'
#    network_mode: host