version: "3"

#keycloak: https://keycloak.zhongfu.net:9443/
#ui: https://ui.zhongfu.net:9443/

services:

  mariadb:
    image: mariadb:latest
    container_name: "mariadb"
    #    restart: always
    environment:
      MYSQL_USER: "db_user"
      MYSQL_PASSWORD: "db_pwd"
      MYSQL_ROOT_PASSWORD: "root"
      TZ: "Asia/Shanghai"
      MYSQL_DATABASE: "kc_db"
#    volumes:
#      - "./mysql-initdb.d:/docker-entrypoint-initdb.d"
    ports:
      - "3306:3306"


  keycloak:
    image: quay.io/keycloak/keycloak:latest
    #    restart: always
    container_name: "keycloak"
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: "mariadb"
      KC_DB_URL: "jdbc:mariadb://mariadb:3306/kc_db?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&allowPublicKeyRetrieval=true"
      KC_DB_USERNAME: db_user
      KC_DB_PASSWORD: db_pwd
    depends_on:
      - mariadb
    command: 'start-dev'
#    network_mode: host

