apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-master
  labels:
    pv: nfs-master
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  nfs:
    path: /nfs/es/
    server: 192.168.1.102  #master Node IP